# Generated by Django 5.2.3 on 2026-01-27 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(10000)], verbose_name='Conteúdo'),
        ),
    ]
