# Generated by Django 5.2.3 on 2025-12-26 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_note_alter_todo_options_alter_todo_deadline_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
